/**
 * GLB Model Validator — cross-checks a GLB file against all hardcoded mesh
 * dependencies in the codebase. Catches silent breakage before it ships.
 *
 * Run:  npm run validate-model
 * Or:   node scripts/validate-model.mjs [path-to-glb]
 *
 * Exit code 0 = all checks pass, 1 = warnings/errors found.
 */
import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Mesh dependencies (mirrors the source files exactly) ─────────────────────

/** src/config/modelMap.js — every key must exist in the GLB */
// Runtime mesh names (what Three.js GLTFLoader actually produces). See
// src/config/modelMap.js for the naming rules. Verified by live-scene dump.
const MODEL_MAP_MESHES = [
  // Stages
  'Roundcube_1', 'Roundcube_2', 'Roundcube001_1', 'Roundcube001_2',
  'Cylinder', 'Cylinder001',
  'Cube_1', 'Cube_2', 'Cube_3',
  'Cube001_1', 'Cube001_2', 'Cube001_3', 'Cube001_4',
  'Cylinder002_1', 'Cylinder002_2',
  // Envelop — "Hill Shades" node (single-prim), sanitized to "Hill_Shades"
  'Hill_Shades',
  // Food — Cube.005 is shared by 3 GLTF nodes → 6 runtime meshes via collision-resolution
  'Cube002_1', 'Cube002_2',
  'Cube005', 'Cube005_1', 'Cube005_2', 'Cube005_3', 'Cube005_4', 'Cube005_5',
  'maposm_buildings009_1', 'maposm_buildings009_2', 'maposm_buildings009_3',
  // Foundry
  'Roundcube002_1', 'Roundcube002_2', 'Roundcube003_1', 'Roundcube003_2', 'Roundcube004',
  // Bodega — node "Large Tent" / mesh Cone.001 (single-prim, space→underscore)
  'Large_Tent',
  // Camping — new explicit node in 23/04/2026 model
  'Placement_CampingTents',
  // Glamping
  'Cube009_1', 'Cube009_2',
  // Glamping RVs — Placement_ParkingLot.001 node, mesh Cube.017 (2 prims)
  'Cube017', 'Cube017_1',
  // Restrooms
  'BathroomGA002', 'BathroomGA003', 'BathroomGA012', 'BathroomGA001',
  // Guest Services (split at runtime — _gs suffix; _nonGS portion is non-interactive)
  'maposm_buildings011_1', 'maposm_buildings011_2', 'maposm_buildings011_3',
  // Note: runtime names maposm_buildings011_N_gs/_nonGS are generated by model.js
  // Shop — map.osm_buildings.008 (3 prims, same as GitHub release)
  'maposm_buildings008_1', 'maposm_buildings008_2', 'maposm_buildings008_3',
  // Bars — bar-1 = BarLocation.000, bar-2 = BarLocation.001
  'Cube003_1', 'Cube003_2',
  'Cube004_1', 'Cube004_2',
];

/** src/scene/model.js — HIDDEN_MESHES */
const HIDDEN_MESHES = [
  'CampingTent',
  'Truck', 'Van', 'Car', 'Hatchback',
  'Truck001', 'Van001', 'Car001', 'Hatchback002',
  'Car002', 'Car003', 'Car005',
];

/** src/scene/model.js — NO_SHADOW_CAST */
const NO_SHADOW_CAST = ['maposm_roads_residential', 'Road_Trimmed', 'Plane002', 'Plane003'];

/** src/scene/model.js — terrain mesh for BackSide self-shadows */
const TERRAIN_MESH = 'Terrain_Step_Terrace_CamCrop';

/** src/scene/water.js — pool surface that gets the water shader (4th prim of Cube.001) */
const POOL_MESH = 'Cube001_4';

/** All mesh names the code references */
const ALL_EXPECTED = new Set([
  ...MODEL_MAP_MESHES,
  ...HIDDEN_MESHES,
  ...NO_SHADOW_CAST,
  TERRAIN_MESH,
  POOL_MESH,
]);

// ── GLB parser ───────────────────────────────────────────────────────────────

/**
 * Mirrors Three.js PropertyBinding.sanitizeNodeName():
 * strips dots and some reserved characters so the runtime mesh name matches.
 * e.g. "Roundcube.001" → "Roundcube001", "map.osm_buildings.009" → "maposm_buildings009"
 */
/**
 * Mirrors Three.js PropertyBinding.sanitizeNodeName():
 *   - Strips ".[]" entirely
 *   - Replaces whitespace / a set of reserved chars with "_"
 * e.g. "Roundcube.001" → "Roundcube001", "Large Tent" → "Large_Tent".
 */
function sanitizeName(name) {
  return name.replace(/[.\[\]]/g, '').replace(/[\s\\/:]/g, '_');
}

/**
 * For multi-primitive meshes, Three.js may name children using either the
 * node name or the mesh definition name, depending on whether they differ
 * and on internal collision resolution (createUniqueName). Suffixes can be
 * `_1/_2/_3` for all children, OR `base/_1/_2` (base name without suffix
 * for the first primitive).
 *
 * Rather than replicating every edge case, we generate ALL plausible names
 * from both sources. A code-expected name is "found" if it appears anywhere
 * in this set. False negatives are far worse than false positives here —
 * a missed rename silently breaks interactivity.
 */
function expandMultiPrim(baseName, primCount) {
  const names = new Set();
  // Pattern A: _1, _2, _3 (all suffixed)
  for (let i = 1; i <= primCount; i++) names.add(`${baseName}_${i}`);
  // Pattern B: base, _1, _2 (first unsuffixed)
  names.add(baseName);
  for (let i = 1; i < primCount; i++) names.add(`${baseName}_${i}`);
  return names;
}

function extractMeshNames(glbPath) {
  const buf = readFileSync(glbPath);

  // GLB header: magic(4) + version(4) + length(4)
  const magic = buf.readUInt32LE(0);
  if (magic !== 0x46546C67) {
    throw new Error(`Not a valid GLB file (magic: 0x${magic.toString(16)})`);
  }

  // First chunk must be JSON
  const chunkLength = buf.readUInt32LE(12);
  const chunkType = buf.readUInt32LE(16);
  if (chunkType !== 0x4E4F534A) {
    throw new Error('First GLB chunk is not JSON');
  }

  const json = JSON.parse(buf.slice(20, 20 + chunkLength).toString('utf8'));

  // Collect all plausible runtime mesh names, simulating Three.js
  // GLTFLoader's createUniqueName counter. The counter is shared across ALL
  // nodeName reservations AND mesh-prim naming calls, so we need to process
  // nodes in order and track the same counter registry.
  const meshNames = new Set();
  const nodeNames = [];
  const nameMap = new Map();

  // Shared createUniqueName counter registry (mirrors GLTFLoader.nodeNamesUsed).
  const usedNames = Object.create(null);
  const reserve = (rawName) => {
    const base = sanitizeName(rawName || '');
    if (base in usedNames) return base + '_' + (++usedNames[base]);
    usedNames[base] = 0;
    return base;
  };

  if (json.nodes) {
    // Phase 1 — reserve every nodeName FIRST (mirrors GLTFLoader line 4207
    // which runs synchronously for each node before mesh prims are created).
    for (const node of json.nodes) {
      if (node.name) {
        nodeNames.push(node.name);
        reserve(node.name); // final mesh names for single-prim come from here
      }
    }

    // Phase 2 — for each node with a mesh, generate names for its primitives.
    for (const node of json.nodes) {
      if (node.mesh === undefined || !node.name) continue;
      const gltfMesh = json.meshes?.[node.mesh];
      const primCount = gltfMesh?.primitives?.length ?? 1;
      const nodeSan = sanitizeName(node.name);
      const meshRaw = gltfMesh?.name ?? node.name;

      if (primCount === 1) {
        // Single-prim: final Mesh.name = nodeName (Line 4279 overrides mesh.name).
        meshNames.add(nodeSan);
        nameMap.set(nodeSan, node.name);
        // NOTE: mesh.name reservation still happens internally (line 3844) and
        // consumes a counter slot, even though the name is then overwritten.
        // We mirror that so later multi-prim collisions line up correctly.
        reserve(meshRaw);
      } else {
        // Multi-prim: each primitive's Mesh.name = createUniqueName(meshName).
        for (let i = 0; i < primCount; i++) {
          const runtimeName = reserve(meshRaw);
          meshNames.add(runtimeName);
          nameMap.set(runtimeName, `${gltfMesh?.name || node.name} [prim ${i} of ${node.name}]`);
        }
      }
    }
  }

  return { meshNames, nodeNames, nameMap, json };
}

// ── Validation ───────────────────────────────────────────────────────────────

function validate(glbPath) {
  console.log(`\n  GLB Model Validator`);
  console.log(`  ${'─'.repeat(50)}`);
  console.log(`  File: ${glbPath}\n`);

  let meshNames, nodeNames, nameMap, json;
  try {
    ({ meshNames, nodeNames, nameMap, json } = extractMeshNames(glbPath));
  } catch (err) {
    console.error(`  ERROR: ${err.message}`);
    process.exit(1);
  }

  console.log(`  Total nodes in GLB:          ${nodeNames.length}`);
  console.log(`  Mesh names (after sanitize): ${meshNames.size}`);
  console.log(`  Expected by code:            ${ALL_EXPECTED.size}\n`);

  let warnings = 0;
  let errors = 0;

  // ── Check 1: Missing meshes (code expects them but GLB doesn't have them)
  console.log('  CHECK 1: Missing meshes (code expects, GLB missing)');
  console.log('  ' + '─'.repeat(50));

  const missingInteractive = MODEL_MAP_MESHES.filter((n) => !meshNames.has(n));
  if (missingInteractive.length > 0) {
    errors += missingInteractive.length;
    console.log(`  ✗ ${missingInteractive.length} interactive mesh(es) MISSING:`);
    missingInteractive.forEach((n) => console.log(`      - ${n}`));
    console.log('    → These buildings will have NO hover/click/highlight.\n');
  } else {
    console.log('  ✓ All interactive meshes present.\n');
  }

  // Special meshes
  const specialChecks = [
    { name: TERRAIN_MESH, role: 'Terrain (self-shadow)', file: 'model.js' },
    { name: POOL_MESH, role: 'Pool water surface', file: 'water.js' },
    ...NO_SHADOW_CAST.map((n) => ({ name: n, role: 'Road (no-shadow-cast)', file: 'model.js' })),
    ...HIDDEN_MESHES.map((n) => ({ name: n, role: 'Hidden mesh', file: 'model.js' })),
  ];

  console.log('  CHECK 2: Special meshes');
  console.log('  ' + '─'.repeat(50));
  for (const { name, role, file } of specialChecks) {
    if (meshNames.has(name)) {
      console.log(`  ✓ ${name}  →  ${role}`);
    } else {
      // Hidden meshes are just warnings; others are errors
      if (HIDDEN_MESHES.includes(name)) {
        warnings++;
        console.log(`  ~ ${name}  →  ${role} (OK if intentionally removed)`);
      } else {
        errors++;
        console.log(`  ✗ ${name}  →  ${role} MISSING  [${file}]`);
      }
    }
  }
  console.log();

  // ── Check 3: New meshes (in GLB but not referenced by code)
  // Show only genuinely novel nodes — filter out generated multi-prim variants
  // that exist purely from the dual-naming expansion.
  console.log('  CHECK 3: Unrecognized nodes (in GLB, not in code)');
  console.log('  ' + '─'.repeat(50));

  // Build a set of unique GLB node names (single source of truth from the file)
  const glbNodeMeshNames = new Set();
  if (json.nodes) {
    for (const node of json.nodes) {
      if (node.mesh !== undefined && node.name) {
        glbNodeMeshNames.add(sanitizeName(node.name));
      }
    }
  }
  // A node is "unrecognized" if its sanitized name doesn't appear as a prefix
  // of any expected mesh name (accounts for _1/_2/_3 suffixes)
  const unrecognizedNodes = [...glbNodeMeshNames].filter((nodeName) => {
    // Direct match
    if (ALL_EXPECTED.has(nodeName)) return false;
    // Check if any expected name starts with this node name + "_"
    for (const exp of ALL_EXPECTED) {
      if (exp.startsWith(nodeName + '_') || exp === nodeName) return false;
    }
    return true;
  });

  if (unrecognizedNodes.length > 0) {
    warnings += unrecognizedNodes.length;
    console.log(`  ~ ${unrecognizedNodes.length} GLB node(s) not referenced by code:`);
    unrecognizedNodes.forEach((n) => console.log(`      - ${n}`));
    console.log('    → These are non-interactive. Add to modelMap.js if they should be clickable.\n');
  } else {
    console.log('  ✓ No unrecognized nodes.\n');
  }

  // ── Check 4: Draco compression
  console.log('  CHECK 4: Draco compression');
  console.log('  ' + '─'.repeat(50));
  const hasDraco = json.extensionsUsed?.includes('KHR_draco_mesh_compression') ||
                   json.extensionsRequired?.includes('KHR_draco_mesh_compression');
  if (hasDraco) {
    console.log('  ✓ KHR_draco_mesh_compression detected.\n');
  } else {
    warnings++;
    console.log('  ~ No Draco compression. File will be larger than necessary.');
    console.log('    → Export with Draco enabled in Blender glTF settings.\n');
  }

  // ── Check 5: File size
  console.log('  CHECK 5: File size');
  console.log('  ' + '─'.repeat(50));
  const stats = readFileSync(glbPath);
  const sizeMB = stats.length / 1024 / 1024;
  if (sizeMB > 20) {
    warnings++;
    console.log(`  ~ ${sizeMB.toFixed(2)} MB — consider optimizing (target < 15 MB).`);
  } else {
    console.log(`  ✓ ${sizeMB.toFixed(2)} MB`);
  }
  console.log();

  // ── Summary
  console.log('  ' + '═'.repeat(50));
  if (errors === 0 && warnings === 0) {
    console.log('  ✓ ALL CHECKS PASSED — model is ready for integration.\n');
  } else {
    if (errors > 0) console.log(`  ✗ ${errors} ERROR(S) — must fix before deployment.`);
    if (warnings > 0) console.log(`  ~ ${warnings} WARNING(S) — review recommended.`);
    console.log();
  }

  process.exit(errors > 0 ? 1 : 0);
}

// ── Entry point ──────────────────────────────────────────────────────────────

const glbPath = process.argv[2] || resolve(ROOT, 'public', 'assets', 'model', 'formFestMap.glb');
validate(glbPath);
